# Generated by Django 2.2 on 2021-04-01 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Укажите дату проверки', verbose_name='Дата проверки')),
                ('info', models.TextField(blank=True, help_text='При необходимости укажите дополнительные сведения', max_length=1000, null=True, verbose_name='Сопроводительная информация')),
                ('status', models.BooleanField(default=False, help_text='Укажите текущий статус проверки', null=True, verbose_name='Текущий статус проверки работы')),
                ('docx_file', models.FileField(help_text='Укажите файл с расширением docx', null=True, upload_to='diplomas/%Y/%m/%d/', verbose_name='Дипломная работа (расширение docx)')),
                ('pdf_file', models.FileField(help_text='Укажите файл с расширением pdf', null=True, upload_to='diplomas/%Y/%m/%d/', verbose_name='Дипломная работа (расширение pdf)')),
                ('student', models.ForeignKey(help_text='Выберите студента из списка', on_delete=django.db.models.deletion.CASCADE, related_name='checkout_student', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'ordering': ['check_date'],
            },
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.TextField(help_text='Укажите раздел ПЗ', max_length=100, verbose_name='Раздел ПЗ страницы')),
                ('page_number', models.CharField(blank=True, help_text='Укажите номер страницы', max_length=100, null=True, verbose_name='Номер страницы')),
                ('paragraph', models.CharField(blank=True, help_text='Укажите номер абзаца', max_length=100, null=True, verbose_name='Номер абзаца')),
                ('check_all', models.CharField(blank=True, help_text='При необходимости укажите дополнительные сведения', max_length=100, null=True, verbose_name='Сопроводительная информация')),
                ('text', models.TextField(help_text='Введите текст замечания', max_length=300, verbose_name='Текст замечания')),
                ('check_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Укажите дату публикации замечания', verbose_name='Дата публикации замечания')),
                ('author', models.ForeignKey(help_text='Укажите автора замечания', on_delete=django.db.models.deletion.CASCADE, related_name='remark', to=settings.AUTH_USER_MODEL, verbose_name='Автор замечания')),
                ('check_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remark', to='verify.CheckOut')),
            ],
            options={
                'ordering': ['check_date'],
            },
        ),
    ]
