# Generated by Django 2.2 on 2021-04-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='docx_file',
            field=models.FileField(help_text='Укажите файл с расширением docx, размером не более 8 Мб', null=True, upload_to='diplomas/%Y/%m/%d/', verbose_name='Дипломная работа (расширение docx)'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='pdf_file',
            field=models.FileField(help_text='Укажите файл с расширением pdf, размером не более 8 Мб', null=True, upload_to='diplomas/%Y/%m/%d/', verbose_name='Дипломная работа (расширение pdf)'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='check_all',
            field=models.CharField(blank=True, help_text='Уточните необходимость проверки по всему документу', max_length=100, null=True, verbose_name='Проверить замечания по всему документу'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='section',
            field=models.CharField(help_text='Укажите раздел ПЗ', max_length=100, verbose_name='Раздел ПЗ страницы'),
        ),
    ]
